### ISSUE TITLE
.gitignore file

### ISSUE THREAD

**Issue by nminaya** [andrewyancey/ImageManipulation#1]
This repository has a C# project but the gitignore file is for c++ projects

**Comment by SharpSeeEr** [comment]
There is an entry for `bin` in the gitignore, but it should be `bin/`.  
The gitignore file looks as if it was added after the initial commit, as the big/Debug folder exists and is populated.  You'll need to manually delete those files and folders, then stage and commit the deletions.

**Comment by oneofmanylukes** [comment]
I addressed this issue in pull request #2

**Comment by andrewyancey** [comment]
I believe this has been resolved
