### ISSUE TITLE
Review branch is ready for final review before I merge it into dev.

### ISSUE THREAD

**Issue by andrewyancey** [andrewyancey/ImageManipulation#13]
If you guys wouldn't mind taking a look at it and letting me know what you think. Too big changes are, ImageColor was made to wrap the Color class to perform common operations, and conversion. The RedscaleEffect was reworked so that you can apply it to any channel you would like now.

**Comment by genious97** [comment]
One thing I noticed is that the default channel should be documented

**Comment by genious97** [comment]
Due to the fact that the name was changed to Channel Scale but the Apply action is Redscale

**Comment by andrewyancey** [comment]
Thanks for catching that. That needs to be changed.
